### ISSUE TITLE
Need help some error

### ISSUE THREAD

**Issue by w4567892015** [electron-userland/electron-installer-windows#232] opened 2018-09-14 08:58 UTC
hi ! I have some failed
`Error: Error releasifying package: Error executing command (Exited with status 255):
mono /electron/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify /tmp/electron-76ctMCteg66tfW/tinify-app_1.0.0/nuget/tinify-app.1.0.0.nupkg --releaseDir /tmp/electron-76ctMCteg66tfW/tinify-app_1.0.0/squirrel --setupIcon /electron/node_modules/electron-installer-windows/resources/icon.ico --loadingGif /electron/node_modules/electron-installer-windows/resources/animation.gif
System.AggregateException: One or more errors occurred. ---> System.Exception: Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
wine: Bad EXE format for Z:\electron\node_modules\electron-installer-windows\vendor\squirrel\7z.exe.
  at Squirrel.Utility+<CreateZipFromDirectory>d__23.MoveNext () [0x000ff] in <529cc2cd4af044829f92664c5d854efd>:0
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <2943701620b54f86b436d3ffad010412>:0
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <2943701620b54f86b436d3ffad010412>:0
  at System.Threading.Tasks.Task.Wait () [0x00000] in <2943701620b54f86b436d3ffad010412>:0
  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2[T,TResult] releaseNotesProcessor, System.Action`1[T] contentsPostProcessHook) [0x001f7] in <529cc2cd4af044829f92664c5d854efd>:0
  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, System.Boolean generateMsi, System.String frameworkVersion, System.Boolean generateDeltas) [0x00214] in <529cc2cd4af044829f92664c5d854efd>:0
  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x004a2] in <529cc2cd4af044829f92664c5d854efd>:0
  at Squirrel.Update.Program.main (System.String[] args) [0x00082] in <529cc2cd4af044829f92664c5d854efd>:0
  at Squirrel.Update.Program.Main (System.String[] args) [0x00006] in <529cc2cd4af044829f92664c5d854efd>:0
---> (Inner Exception #0) System.Exception: Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
wine: Bad EXE format for Z:\electron\node_modules\electron-installer-windows\vendor\squirrel\7z.exe.
  at Squirrel.Utility+<CreateZipFromDirectory>d__23.MoveNext () [0x000ff] in <529cc2cd4af044829f92664c5d854efd>:0 <---
    at err (/electron/node_modules/electron-installer-windows/src/installer.js:31:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by fcastilloec** [comment] 2018-10-02 18:45
Could you provide the exact command you run? If you use this module programmatically, copy paste the code you use. The most important thing is showing what options (if any) did you use.

**Comment by fcastilloec** [comment] 2018-10-03 05:02
I was referring to the `electron-installer-windows` command that you use that make the error appear. From what I see of the commands you posted, try uninstalling `nuget`. This module comes with its own `nuget`, so maybe there's a conflict there, which I doubt but it's worth a try.

I also saw that you're getting an X server error, mono is trying to create a window. I'm not sure why, it could be just an MS dialog for you to accept terms, etc.

**Comment by w4567892015** [comment] 2018-10-03 06:11
Okay,I tryed to uninstall nuget, And i run this command 
electron-packager . tinify-app --platform=win32 --arch=x64 --overwrite --icon=./icon.ico --out=dist && electron-installer-windows --src dist/tinify-app-win32-x64/ --dest ${PWD}/dist/

**Comment by fcastilloec** [comment] 2018-11-27 03:49
It seems that this error might be a duplicate of #233 , specifically https://github.com/electron-userland/electron-installer-windows/issues/233#issuecomment-426528338 might have a solution that works for you.

**Closed by fcastilloec** 2018-11-27 03:49 UTC
