### ISSUE TITLE
Error createing package with NuGet: 

### ISSUE THREAD

**Issue by ddelapasse2** [electron-userland/electron-installer-windows#273] opened 2019-05-11 17:59 UTC
**What version of `electron-installer-windows` are you using?**
1.1.1
**What version of `node` and `npm` are you using?**
v10.15.3     6.4.1
**What operating system are you using?**
Win10
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
yes!

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
electron-packager . angular-electron-mstr-dbg --platform win32 --arch x64 --out dld/ --icon src/favicon.ico

electron-installer-windows --src dld/angular-electron-mstr-dbg-win32-x64/ --dest dld/installers/x64/ --config elect-inst-win-cfg.json

**What did you expect to happen?**
no errors

**What actually happened?**
The temp path contains "undefined" which seems bad and the command fails with the message pasted below.   FYI: I do see this file:  C:\Users\Deanna\AppData\Local\Temp\electron-17608LW9bHLQsW4H6\angular-electron-mstr-dbg_5.1.0_undefined\angular-electron-mstr-dbg\resources\app\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\60\51\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64

I have a slightly unusual hierarchy.  Attached a screenshot with that and the full package.json.
Here's an excerpt:
`{
  "name": "angular-electron-mstr-dbg",
  "version": "5.1.0",
  "productName": "Ang-Elec-Mstr-Dbg app",
  "description": "Angular 7 with Electron (Typescript + SASS + Hot Reload)",
  "homepage": "https://github.com/maximegris/angular-electron",
  "author": "Maxime GRIS",
  "keywords": [
    "angular",
    "angular 7",
    "electron",
    "typescript",
    "sass"
  ],
  "main": "edist/main.js",
  "private": true,
   ....`

config file is minimal (removed everything else while debugging)
[package.zip](https://github.com/electron-userland/electron-installer-windows/files/3169329/package.zip)
:
{
    "icon": "src/favicon.ico"
  }

Actual commands

 C:\test_projects\Electron\angular-electron-master-dbg> **electron-installer-windows --src dld/angular-electron-mstr-dbg-win32-x64/ --dest dld/installers/x64/ --config elect-inst-win-cfg.json**
Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Deanna\AppData\Local\Temp\electron-17608LW9bHLQsW4H6\angular-electron-mstr-dbg_5.1.0_undefined\nuget\angular-electron-mstr-dbg.nuspec -BasePath C:\Users\Deanna\AppData\Local\Temp\electron-17608LW9bHLQsW4H6\angular-electron-mstr-dbg_5.1.0_undefined\angular-electron-mstr-dbg -OutputDirectory C:\Users\Deanna\AppData\Local\Temp\electron-17608LW9bHLQsW4H6\angular-electron-mstr-dbg_5.1.0_undefined\nuget -NoDefaultExcludes
Could not find a part of the path 'C:\Users\Deanna\AppData\Local\Temp\electron-17608LW9bHLQsW4H6\angular-electron-mstr-dbg_5.1.0_undefined\angular-electron-mstr-dbg\resources\app\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\60\51\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64'.

    at spawn.then.catch.err (C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\electron-installer-common\src\spawn.js:21:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nC:\\Users\\Deanna\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe pack C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-17608LW9bHLQsW4H6\\angular-electron-mstr-dbg_5.1.0_undefined\\nuget\\angular-electron-mstr-dbg.nuspec -BasePath C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-17608LW9bHLQsW4H6\\angular-electron-mstr-dbg_5.1.0_undefined\\angular-electron-mstr-dbg -OutputDirectory C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-17608LW9bHLQsW4H6\\angular-electron-mstr-dbg_5.1.0_undefined\\nuget -NoDefaultExcludes\nCould not find a part of the path \'C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-17608LW9bHLQsW4H6\\angular-electron-mstr-dbg_5.1.0_undefined\\angular-electron-mstr-dbg\\resources\\app\\node_modules\\.cache\\terser-webpack-plugin\\content-v2\\sha512\\60\\51\\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64\'.\r\n\n    at spawn.then.catch.err (C:\\Users\\Deanna\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\node_modules\\electron-installer-common\\src\\spawn.js:21:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'

**Comment by fcastilloec** [comment] 2019-05-11 18:24
The problem you're having has been reported already. You can see it in #249. A fix has already been issued and merged into the latest branch (#260), but we haven't published a new version yet. That will come soon, we were waiting to also release the new version with some other changes.

**Closed by fcastilloec** 2019-05-11 18:24 UTC
Labels: duplicate

**Comment by ddelapasse2** [comment] 2019-05-11 20:12
I copied the project to a new location and replaced all the instances of the initial name.  Same issue remains.  I delete the dist (angular dist), eDist (electron dist) & dld (installer folder) each time I try.  pkgr3 fails each time error below.  After the packager runs I can execute the .exe successfully from dld\AngElecMstrDbg-win32-x64.  There is still an "undefined" in my path for some reason.

These are the commands:
  "pkgr1": "node postinstall && electron-builder install-app-deps && npm run electron:serve-tsc && ng build",
  "pkgr2": "electron-packager . AngElecMstrDbg --overwrite --platform win32 --arch x64 --out dld/",
  "pkgr3": "electron-installer-windows  --config installerConfig.json"

installerConfig.json
{
    "name": "AngElecMstrDbg",
    "src":"dld/AngElecMstrDbg-win32-x64/",
    "dest": "dld/installers/",
    "icon": "src/favicon.ico",
    "noMsi": true
  }

Top of package.json (complete file attached);
`{
  "name": "AngElecMstrDbg",
  "version": "5.1.0",
  "productName": "AngElecMstrDbg app",
  "description": "Angular 7 with Electron (Typescript + SASS + Hot Reload)",
  "homepage": "https://github.com/maximegris/AngElecMstrDbg",
  "author": "Maxime GRIS",
...`

**Error from the electron-installer-windows line**
`PS C:\test_projects\Electron\AngElecMstrDbg> npm run pkgr3

> AngElecMstrDbg@5.1.0 pkgr3 C:\test_projects\Electron\AngElecMstrDbg
> **electron-installer-windows  --config installerConfig.json**

Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\test_projects\Electron\AngElecMstrDbg\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Deanna\AppData\Local\Temp\electron-9524BZekUtWua34T\AngElecMstrDbg_5.1.0_undefined\nuget\AngElecMstrDbg.nuspec -BasePath C:\Users\Deanna\AppData\Local\Temp\electron-9524BZekUtWua34T\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg -OutputDirectory C:\Users\Deanna\AppData\Local\Temp\electron-9524BZekUtWua34T\AngElecMstrDbg_5.1.0_undefined\nuget -NoDefaultExcludes
Could not find a part of the path 'C:\Users\Deanna\AppData\Local\Temp\electron-9524BZekUtWua34T\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg\resources\app\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\60\51\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64'.

    at spawn.then.catch.err (C:\test_projects\Electron\AngElecMstrDbg\node_modules\electron-installer-common\src\spawn.js:21:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nC:\\test_projects\\Electron\\AngElecMstrDbg\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe pack C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-9524BZekUtWua34T\\AngElecMstrDbg_5.1.0_undefined\\nuget\\AngElecMstrDbg.nuspec -BasePath C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-9524BZekUtWua34T\\AngElecMstrDbg_5.1.0_undefined\\AngElecMstrDbg -OutputDirectory C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-9524BZekUtWua34T\\AngElecMstrDbg_5.1.0_undefined\\nuget -NoDefaultExcludes\nCould not find a part of the path \'C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-9524BZekUtWua34T\\AngElecMstrDbg_5.1.0_undefined\\AngElecMstrDbg\\resources\\app\\node_modules\\.cache\\terser-webpack-plugin\\content-v2\\sha512\\60\\51\\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64\'.\r\n\n    at spawn.then.catch.err (C:\\test_projects\\Electron\\AngElecMstrDbg\\node_modules\\electron-installer-common\\src\\spawn.js:21:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AngElecMstrDbg@5.1.0 pkgr3: `electron-installer-windows  --config installerConfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the AngElecMstrDbg@5.1.0 pkgr3 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Deanna\AppData\Roaming\npm-cache\_logs\2019-05-11T20_01_52_890Z-debug.log`

[files.zip](https://github.com/electron-userland/electron-installer-windows/files/3169437/files.zip)

**Comment by fcastilloec** [comment] 2019-05-11 20:25
I might need the debug output to see what's going on. Can you change your `pkgr3` command to: `DEBUG=electron-installer-windows electron-installer-windows --config installerConfig.json`
This command will only work if you run it under **bash**, powershelll or command prompt tend to not work well with debugging.

**Comment by ddelapasse2** [comment] 2019-05-11 21:00
Here you go.  Appreciate you looking into this!

ddelapasse@DESKTOP-0PRT2GK MINGW64 /c/test_projects/Electron/AngElecMstrDbg
$ DEBUG=electron-installer-windows electron-installer-windows --config installerConfig.json
Creating package (this may take a while)
  electron-installer-windows Reading package metadata from dld\AngElecMstrDbg-win32-x64\resources\app\package.json +0ms
  electron-installer-windows Creating package with options
  electron-installer-windows {
  electron-installer-windows   "config": "installerConfig.json",
  electron-installer-windows   "name": "AngElecMstrDbg",
  electron-installer-windows   "src": "dld/AngElecMstrDbg-win32-x64/",
  electron-installer-windows   "dest": "dld/installers/",
  electron-installer-windows   "icon": "src/favicon.ico",
  electron-installer-windows   "noMsi": true,
  electron-installer-windows   "bin": "AngElecMstrDbg",
  electron-installer-windows   "execArguments": [],
  electron-installer-windows   "categories": [
  electron-installer-windows     "GNOME",
  electron-installer-windows     "GTK",
  electron-installer-windows     "Utility"
  electron-installer-windows   ],
  electron-installer-windows   "description": "Angular 7 with Electron (Typescript + SASS + Hot Reload)",
  electron-installer-windows   "genericName": "AngElecMstrDbg app",
  electron-installer-windows   "homepage": "https://github.com/maximegris/AngElecMstrDbg",
  electron-installer-windows   "mimeType": [],
  electron-installer-windows   "productDescription": "Angular 7 with Electron (Typescript + SASS + Hot Reload)",
  electron-installer-windows   "productName": "AngElecMstrDbg app",
  electron-installer-windows   "revision": "1",
  electron-installer-windows   "version": "5.1.0",
  electron-installer-windows   "copyright": "Copyright © 2019 Maxime GRIS",
  electron-installer-windows   "authors": [
  electron-installer-windows     "Maxime GRIS"
  electron-installer-windows   ],
  electron-installer-windows   "owners": [
  electron-installer-windows     "Maxime GRIS"
  electron-installer-windows   ],
  electron-installer-windows   "exe": "AngElecMstrDbg.exe",
  electron-installer-windows   "animation": "C:\\Users\\Deanna\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\resources\\animation.gif",
  electron-installer-windows   "requireLicenseAcceptance": false,
  electron-installer-windows   "tags": []
  electron-installer-windows } +6ms
  electron-installer-windows Creating spec file at C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget\AngElecMstrDbg.nuspec +9ms
  electron-installer-windows Creating package at C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined +3s
  electron-installer-windows Executing command C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget\AngElecMstrDbg.nuspec -BasePath C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg -OutputDirectory C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget -NoDefaultExcludes +2ms
  electron-installer-windows Error creating package: Error creating package with NuGet: Error executing command (Exited with status 1):
  electron-installer-windows C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget\AngElecMstrDbg.nuspec -BasePath C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg -OutputDirectory C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget -NoDefaultExcludes
  electron-installer-windows Could not find a part of the path 'C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg\resources\app\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\60\51\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64'.
  electron-installer-windows  +3s
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\nuget.exe pack C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget\AngElecMstrDbg.nuspec -BasePath C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg -OutputDirectory C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\nuget -NoDefaultExcludes
Could not find a part of the path 'C:\Users\Deanna\AppData\Local\Temp\electron-8384x4rsubL472tT\AngElecMstrDbg_5.1.0_undefined\AngElecMstrDbg\resources\app\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\60\51\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64'.

    at spawn.then.catch.err (C:\Users\Deanna\AppData\Roaming\npm\node_modules\electron-installer-windows\node_modules\electron-installer-common\src\spawn.js:21:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nC:\\Users\\Deanna\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\nuget.exe pack C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-8384x4rsubL472tT\\AngElecMstrDbg_5.1.0_undefined\\nuget\\AngElecMstrDbg.nuspec -BasePath C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-8384x4rsubL472tT\\AngElecMstrDbg_5.1.0_undefined\\AngElecMstrDbg -OutputDirectory C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-8384x4rsubL472tT\\AngElecMstrDbg_5.1.0_undefined\\nuget -NoDefaultExcludes\nCould not find a part of the path \'C:\\Users\\Deanna\\AppData\\Local\\Temp\\electron-8384x4rsubL472tT\\AngElecMstrDbg_5.1.0_undefined\\AngElecMstrDbg\\resources\\app\\node_modules\\.cache\\terser-webpack-plugin\\content-v2\\sha512\\60\\51\\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64\'.\r\n\n    at spawn.then.catch.err (C:\\Users\\Deanna\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\node_modules\\electron-installer-common\\src\\spawn.js:21:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'

**Comment by ddelapasse2** [comment] 2019-05-13 11:54
Could you reopen this ticket since it's still not working after renaming?  Also, here is the updated installConfig.json (added name here as well per the other ticket and added 'noMsi' as well):

{
    "name": "AngElecMstrDbg",
    "src":"dld/AngElecMstrDbg-win32-x64/",
    "dest": "dld/installers/",
    "icon": "src/favicon.ico",
    "noMsi": true
  }

**Comment by fcastilloec** [comment] 2019-05-13 17:31
Thanks for the debug, but there's really nothing wrong and I can't reproduce this.
You're seeing `undefinded` in the path because we use `electron-installer-common` for this module, and it generates the path with the `arch`. Windows doesn't care about `arch` for its installers but others, like Linux, do. So disregard that, it's all normal and meant to be that way.

The error you're seeing is that module can't find `node_modules\\.cache\\terser-webpack-plugin\\content-v2\\sha512\\60\\51\\c86b830fc8e719450b45526649bef4cb30257b3968a5bc067720f8f10a5e50ea3c72ea8efb40cee0c87d319bdc8990df8c849f181bc0763db7154451fd64`, this is specific to just your setup and not a bug with this module.
You should verify that that path exists. Make sure that you rebuild with `electron-packager` after you changed the names. Also, make sure that your dependencies are correctly grouped, that way `electron-packager` can ignore anything listed under `devDependencies`. I don't know how you're project is organized, but I'm pretty sure that `teser-webpack-plugin` should be listed in `devDependencies` and not in `dependencies`, but then again, I'm not sure what your app does and you might actually depend on that package.

Sorry I can't be of more help, but it seems that this is not a bug with our module.
